export const LOAD_TOP_CATEGORIES_SUCCESS = 'pages/Event/LOAD_TOP_CATEGORIES_SUCCESS'
export const LOAD_EVENTS_SUCCESS = 'pages/Event/LOAD_EVENTS_SUCCESS'
export const FOLLOW_EVENT_SUCCESS = 'pages/Event/FOLLOW_EVENT_SUCCESS'
export const UNFOLLOW_EVENT_SUCCESS = 'pages/Event/UNFOLLOW_EVENT_SUCCESS'
