export const GET_CHATS_SUCCESS = 'pages/StreamManager/GET_CHATS_SUCCESS'
export const LOAD_TAG_SUCCESS = 'pages/StreamManager/LOAD_TAG_SUCCESS'
export const LOAD_STREAM_CONFIG_SUCCESS = 'pages/StreamManager/LOAD_STREAM_CONFIG_SUCCESS'
export const CLEAR_PUSH_NOTIFICATIONS = 'pages/StreamManager/CLEAR_PUSH_NOTIFICATIONS'
export const ADD_NEW_STREAM_SESSION = 'pages/StreamManager/ADD_NEW_STREAM_SESSION'
export const LOAD_CATEGORY_SUCCESS = 'pages/StreamManager/LOAD_CATEGORY_SUCCESS'
export const LOAD_STREAM_MEDIA_SOURCE_SUCCESS =
  'pages/StreamManager/LOAD_STREAM_MEDIA_SOURCE_SUCCESS'
export const PUBLISH_STREAM_SESSION_REQUESTED =
  'pages/StreamManager/PUBLISH_STREAM_SESSION_REQUESTED'
export const PUBLISH_STREAM_SESSION_SUCCESS =
  'pages/StreamManager/PUBLISH_STREAM_SESSION_SUCCESS'
export const PUBLISH_STREAM_SESSION_FAIL =
  'pages/StreamManager/PUBLISHING_STREAM_SESSION_FAIL'
export const FINISH_STREAM_SESSION_SUCCESS =
  'pages/StreamManager/FINISH_STREAM_SESSION_SUCCESS'
