export const TOGGLE_SIDEBAR = 'app/TOGGLE_SIDE_BAR'
export const LOGOUT = 'app/LOGOUT'
export const GET_CURRENT_USER_INFO_SUCCESS = 'app/GET_CURRENT_USER_INFO_SUCCESS'
export const GET_FOLLOWING_STREAM_SESSION_SUCCESS =
  'app/GET_FOLLOWING_STREAM_SESSION_SUCCESS'
export const GET_RECOMMEND_STREAM_SESSION_SUCCESS =
  'app/GET_RECOMMEND_STREAM_SESSION_SUCCESS'
export const GET_FOLLOWING_USERS_SUCCESS = 'app/GET_FOLLOWING_USERS_SUCCESS'
export const ADD_NEW_NOTIFICATION = 'app/ADD_NEW_NOTIFICATION'
