export const LOAD_STREAM_SEARCH_SUCCESS = 'pages/Search/LOAD_STREAM_SUCCESS'
export const LOAD_USER_SEARCH_SUCCESS = 'pages/Search/LOAD_USER_SEARCH_SUCCESS'
export const LOAD_CATEGORIES_SEARCH_SUCCESS = 'pages/Search/LOAD_CATEGORY_SEARCH_SUCCESS'
